/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'a' at '1/18/18 9:26 AM' with Gradle 2.14.1
 *
 * @author a, @date 1/18/18 9:26 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
